name: Lox-rs CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Build release binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

  run-examples:
    name: Run Examples
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build release binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Create examples directory
        run: mkdir -p examples

      - name: Create assign example
        run: |
          cat > examples/assign.lox << 'EOF'
          var a = 1;
          var b = 2;
          b = 3;
          print a + b;
          EOF

      - name: Create branching example
        run: |
          cat > examples/branching.lox << 'EOF'
          var a = 1;
          if (a > 2) 
              print "Greater than two"; 
          else 
              print "Less than two";
          EOF

      - name: Create fibonacci_for example
        run: |
          cat > examples/fibonacci_for.lox << 'EOF'
          var a = 0;
          var temp;

          // fibonacci
          for (var b = 1; a < 1000; b = temp + b) {
            print a;
            temp = a;
            a = b;
          }
          EOF

      - name: Create logical example
        run: |
          cat > examples/logical.lox << 'EOF'
          print "hi" or 2; // "hi".
          print nil or "yes"; // "yes".
          EOF

      - name: Create print example
        run: |
          cat > examples/print.lox << 'EOF'
          print "one";
          print true;
          print 2 + 1;
          EOF

      - name: Create scope example
        run: |
          cat > examples/scope.lox << 'EOF'
          var a = "global a";
          var b = "global b";
          var c = "global c";
          {
            var a = "outer a";
            var b = "outer b";
            {
              var a = "inner a";
              print a;
              print b;
              print c;
            }
            print a;
            print b;
            print c;
          }
          print a;
          print b;
          print c;
          EOF

      - name: Create fibonacci_while example
        run: |
          cat > examples/fibonacci_while.lox << 'EOF'
          var a = 0;
          var b = 1;

          // fibonacci
          while (a < 100) {
            print a;
            var temp = a;
            a = b;
            b = temp + b;
          }
          EOF

      - name: Run examples
        run: |
          echo "Running assign.lox:"
          ./target/release/lox_interpreter_rs examples/assign.lox

          echo -e "\nRunning branching.lox:"
          ./target/release/lox_interpreter_rs examples/branching.lox

          echo -e "\nRunning logical.lox:"
          ./target/release/lox_interpreter_rs examples/logical.lox

          echo -e "\nRunning print.lox:"
          ./target/release/lox_interpreter_rs examples/print.lox

          echo -e "\nRunning scope.lox:"
          ./target/release/lox_interpreter_rs examples/scope.lox

          echo -e "\nRunning fibonacci_for.lox (first 10 numbers):"
          ./target/release/lox_interpreter_rs examples/fibonacci_for.lox | head -10

          echo -e "\nRunning fibonacci_while.lox (first 10 numbers):"
          ./target/release/lox_interpreter_rs examples/fibonacci_while.lox | head -10
